# Lab 3 (10/16)

## Part 2
Data description I didn't do

![A hare!](https://thumb.wikimedia.org/wikipedia/commons/thumb/8/8a/SNOWSHOE_HARE_%28Lepus_americanus%29_%285-28-2015%29_quoddy_head%2C_washington_co%2C_maine_-01_%2818988734889%29.jpg/1920px-SNOWSHOE_HARE_%28Lepus_americanus%29_%285-28-2015%29_quoddy_head%2C_washington_co%2C_maine_-01_%2818988734889%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=index&utm_content=thumbnail&_=20170313021652)

## Part 3

In [23]:
import pandas as pd
import numpy as np
from pathlib import Path

hares = pd.read_csv(Path.home() / "Downloads" / "55_Hare_Data_2012.txt")

hares.head()

,date,time,grid,trap,l_ear,r_ear,sex,age,weight,hindft,notes,b_key,session_id,study
0,11/26/1998,NaN,bonrip,1A,414D096A08,NaN,NaN,NaN,1370.0,160.0,NaN,917.0,51,Population
1,11/26/1998,NaN,bonrip,2C,414D320671,NaN,M,NaN,1430.0,NaN,NaN,936.0,51,Population
2,11/26/1998,NaN,bonrip,2D,414D103E3A,NaN,M,NaN,1430.0,NaN,NaN,921.0,51,Population
3,11/26/1998,NaN,bonrip,2E,414D262D43,NaN,NaN,NaN,1490.0,135.0,NaN,931.0,51,Population
4,11/26/1998,NaN,bonrip,3B,414D2B4B58,NaN,NaN,NaN,1710.0,150.0,NaN,933.0,51,Population

In [2]:
hares.dtypes

date           object
time           object
grid           object
trap           object
l_ear          object
r_ear          object
sex            object
age            object
weight        float64
hindft        float64
notes          object
b_key         float64
session_id      int64
study          object
dtype: object

In [3]:
hares.isna().sum()

date             0
time          3116
grid             0
trap            12
l_ear           48
r_ear          169
sex            352
age           2111
weight         535
hindft        1747
notes         3137
b_key           47
session_id       0
study          163
dtype: int64

In [4]:
hares.shape

(3380, 14)

In [5]:
print(hares['weight'].max())
print(hares['weight'].min())

2365.0
0.0

In [6]:
print(hares['grid'].value_counts())
print(hares['trap'].value_counts())

grid
bonrip     2030
bonbs       929
bonmat      260
Bonbs       152
bonmat        9
Name: count, dtype: int64
trap
3e     75
1c     65
1e     64
2e     61
4c     60
       ..
1e      1
6b      1
2c      1
5c      1
4b      1
Name: count, Length: 121, dtype: int64

## Part 4

In [7]:
hares['sex'].value_counts()

sex
F     1161
M      730
f      556
m      515
?       40
F?      10
f        4
m        4
f?       3
M?       2
m?       2
pf       1
Name: count, dtype: int64

| Sex    | Count |
| ------ | ----- |
| F      | 1161  |
| M      | 730   |

In [8]:
hares['sex'].value_counts(dropna= False)
# returns how many na values there are too

sex
F      1161
M       730
f       556
m       515
NaN     352
?        40
F?       10
f         4
m         4
f?        3
M?        2
m?        2
pf        1
Name: count, dtype: int64

In [9]:
hares[hares.duplicated()] # 4 duplicated rows

,date,time,grid,trap,l_ear,r_ear,sex,age,weight,hindft,notes,b_key,session_id,study
2893,7/1/2011,NaN,bonbs,10a,NaN,NaN,NaN,NaN,NaN,NaN,juvenile,NaN,23,Population
2894,7/1/2011,NaN,bonbs,10a,NaN,NaN,NaN,NaN,NaN,NaN,juvenile,NaN,23,Population
2895,7/1/2011,NaN,bonbs,10a,NaN,NaN,NaN,NaN,NaN,NaN,juvenile,NaN,23,Population
3071,9/11/2012,NaN,bonbs,10d,b2834,b2835,f,j,840.0,114.0,NaN,838.0,31,Population

The sex column has a lot of different values. There could be repeats. Some have a question mark after, so the people who input the data don't even know the sex.

## Part 5

Steps to data wrangling: 
- convert the lower case f/m to the same thing, stripping them of spaces
- get rid of the question marks after f/m
- turn the ? into missing value
- turn the f/m and F/M into female and male

## Part 6

In [24]:
hares['sex_simple'] = hares['sex'].str.lower()
hares['sex_simple'] = hares['sex_simple'].str[:1]
hares['sex_simple'].value_counts(dropna=False)

sex_simple
f      1734
m      1253
NaN     352
?        40
p         1
Name: count, dtype: int64

In [25]:
hares.loc[(hares['sex_simple'] == '?') | (hares['sex_simple'] == 'p')] = np.nan

In [31]:
hares['sex_simple'] = hares['sex_simple'].replace(to_replace= 'f', value= 'female')
hares['sex_simple'] = hares['sex_simple'].replace(to_replace= 'm', value= 'male')

In [32]:
hares['sex_simple'].value_counts(dropna=False)

sex_simple
female    1734
male      1253
NaN        393
Name: count, dtype: int64

In [ ]:
# another simple .str and mapping option
#sex_map = {'f': 'female', 'm': 'male'}

#hares['sex_simple'] = (hares['sex'].str.strip().str.lower().map(sex_map))

## Part 7

In [ ]:
hares_valid = hares[hares['weight'] > 0]
hares_valid[['sex_simple', 'weight']].groupby('sex_simple').mean('weight')

                 weight
sex_simple
female      1363.246053
male        1350.194643

## Part 8

In [ ]:
# Importing packages and data
import pandas as pd
import numpy as np
from pathlib import Path
hares = pd.read_csv(Path.home() / "Downloads" / "55_Hare_Data_2012.txt")

# 
hares['sex_simple'] = hares['sex'].str.lower().str[:1]